# 配置变量
config:
  # 监听端口 2323
  port: 2323
  # 线程池 - 保持线程数 100
  thread-pool: 100
  # 超时时间 30000
  time-out: 30000
  # 税点封顶值
  tax: 0.08
  # 电签税点封顶值
  dq-tax: 0.09
  # ip地址
  ip: 127.0.0.1
  # 生产key,android,iOS 合一
  app_key: 1586132504ee0e4110b974f4
  master_secret: bef803d3b9d7ef657435d646
  # ios蒲公英key
  app_keyios: ea43a2f3577d83f6118f0efa
  master_secretios: 65d65440ada677da35851a73

# mybatis配置
mybatis:
  # mapper的接口xml文件的地址
  mapper-locations: mybatise/mapper/*.xml
  configLocation: classpath:mybatise/sqlMapConfig.xml

# 数据库源配置
spring:
  datasource:
    url: jdbc:oracle:thin:@//192.168.1.70:1521/dba
    username: qb_web
    password: qb_web
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    validationQuery: select 1 from dual
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    filters: mergeStat
